<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Content-Style-Type" content="text/css" /><meta name="generator" content="Aspose.Words for .NET 19.9" /><title></title></head><body><div><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">Answer: Yes, it is possible to write several catch blocks under a single try block. However, the approach needs to be from specific to general. Following example</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">demonstrates the same:</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">public class Example {</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">public static void main(String args[]) {</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">try {</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">int a[]= new int[10];</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">a[10]= 10/0;</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">catch(ArithmeticException e)</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">System.out.println("Arithmetic exception in first catch block");</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">catch(ArrayIndexOutOfBoundsException e)</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">System.out.println("Array index out of bounds in second catch block");</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">catch(Exception e)</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">System.out.println("Any exception in third catch block");</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri; -aw-import:ignore">&#xa0;</span></p></div></body></html>